### ISSUE TITLE
Windows 10 cc1.exe error

### ISSUE THREAD

**Issue by atomi** [cratonica/trayhost#7]
```
$go get github.com/cratonica/trayhost
# github.com/cratonica/trayhost
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

```
$go version
go version go1.4.2 windows/amd64
```

**Comment by adamgoose** [comment]
Try `export GOARCH=386`, then running `go get` again.

**Comment by atomi** [comment]
I'm no longer using Windows. Feel free to close. Thanks.

**Comment by dmitshur** [comment]
Ok, I'll close since this issue is pretty old (go1.4.2) and may no longer be applicable. If it's still an issue with latest versions of Go, it can be re-opened or new one made.
